### ISSUE TITLE
X value to big for scale

### ISSUE THREAD

**Issue by madding1602** [EX0l0N/ply-to-SculptrVR-csv#3]
When I get the ply file to make it a csv file, it appears during a long range the line X value to big for scale

**Comment by EX0l0N** [comment]
As [stated here](https://github.com/EX0l0N/ply-to-SculptrVR-csv#preperations) your model is required to fit into a bounding box of [-1, 1] in all three dimensions.

This limitation is due to the fact that SculptrVR itself does not provide an unlimited space for you to work in, but a cubic volume.

As a result of that a value smaller than -1 or larger than 1 for any of your coordinates can not be projected inside SculptrVRs cube.

Please scale your ply file accordingly using Meshlab or any other tool of your choice.

**Comment by eric-schleicher** [comment]
@madding1602 these videos may be helpful for you: 
transform (center origin): 
https://www.youtube.com/watch?v=OzqHFxej0hg

scale: 
https://www.youtube.com/watch?v=6psAppbOOXM

The Transform:Scale Filter has a option box for scaling to unit bbox which will ensure it fits.
